# Generated by Django 3.2.6 on 2021-09-15 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=40)),
                ('Category_Discription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=40)),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Product_Discription', models.CharField(max_length=100)),
                ('Product_Price', models.IntegerField()),
                ('Product_Stock', models.IntegerField()),
                ('Product_Stock_Status', models.BooleanField()),
                ('Product_Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Commodity.category')),
            ],
        ),
    ]
