# Generated by Django 3.2.7 on 2021-10-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor', '0002_rename_vendor_vendors'),
        ('Commodity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Vendor.vendors'),
        ),
    ]
