# Generated by Django 3.2.6 on 2021-09-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
