# Generated by Django 3.2.6 on 2021-09-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('customer', 'customer'), ('driver', 'driver')], max_length=30, null=True),
        ),
    ]
