# Generated by Django 3.2.6 on 2021-09-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_orderdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_model',
        ),
    ]
