# Generated by Django 3.2.7 on 2021-09-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('customer', 'customer'), ('driver', 'driver')], default='customer', max_length=30, null=True),
        ),
    ]
