# Generated by Django 3.2.7 on 2021-10-06 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Commodity', '0001_initial'),
        ('Products', '0010_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.order')),
                ('a_product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Commodity.product')),
                ('a_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
