# Generated by Django 3.2.7 on 2021-10-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_addtocart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='a_order',
        ),
    ]
