# Generated by Django 3.2.7 on 2021-10-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_remove_addtocart_a_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
