# Generated by Django 3.2.7 on 2021-10-07 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Commodity', '0001_initial'),
        ('Products', '0015_auto_20211006_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbwishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aproduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Commodity.product')),
                ('auser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
